# Build the manager binary
FROM golang:1.21 as bpfman-agent-build
ARG TARGETOS
ARG TARGETARCH

WORKDIR /usr/src/bpfman/

# Copy the Go Modules manifests
COPY go.mod go.mod
COPY go.sum go.sum

# cache deps before building and copying source so that we don't need to re-download as much
# and so that source changes don't invalidate our downloaded layer
RUN go mod download

# Copy the go source
COPY . .

# Build
# the GOARCH has not a default value to allow the binary be built according to the host where the command
# was called. For example, if we call make docker-build in a local env which has the Apple Silicon M1 SO
# the docker BUILDPLATFORM arg will be linux/arm64 when for Apple x86 it will be linux/amd64. Therefore,
# by leaving it empty we can ensure that the container and binary shipped on it will have the same platform.
WORKDIR /usr/src/bpfman/bpfman-operator
RUN CGO_ENABLED=0 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} go build -a -o bpfman-agent ./cmd/bpfman-agent/main.go

# Use the fedora minimal image to reduce the size of the final image but still
# be able to easily install extra packages.

# The full fedora image can be used for debugging purposes, but you may need to
# change "microdnf" to "dnf" below to install extra packages.
# FROM fedora:38
FROM quay.io/fedora/fedora-minimal
ARG TARGETARCH
WORKDIR /
COPY --from=bpfman-agent-build /usr/src/bpfman/bpfman-operator/bpfman-agent .

# Install crictl
RUN microdnf -y install wget tar
ARG VERSION="v1.28.0"
RUN wget https://github.com/kubernetes-sigs/cri-tools/releases/download/${VERSION}/crictl-${VERSION}-linux-${TARGETARCH}.tar.gz
RUN tar zxvf crictl-${VERSION}-linux-${TARGETARCH}.tar.gz -C /usr/local/bin
RUN rm -f crictl-${VERSION}-linux-${TARGETARCH}.tar.gz
RUN microdnf -y clean all

ENTRYPOINT ["/bpfman-agent"]
