//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BpfNetworkMultiAttach) DeepCopyInto(out *BpfNetworkMultiAttach) {
	*out = *in
	if in.ProceedOn != nil {
		in, out := &in.ProceedOn, &out.ProceedOn
		*out = make([]ProceedOnValue, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BpfNetworkMultiAttach.
func (in *BpfNetworkMultiAttach) DeepCopy() *BpfNetworkMultiAttach {
	if in == nil {
		return nil
	}
	out := new(BpfNetworkMultiAttach)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BpfProgram) DeepCopyInto(out *BpfProgram) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BpfProgram.
func (in *BpfProgram) DeepCopy() *BpfProgram {
	if in == nil {
		return nil
	}
	out := new(BpfProgram)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BpfProgram) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BpfProgramAttachPoint) DeepCopyInto(out *BpfProgramAttachPoint) {
	*out = *in
	if in.NetworkMultiAttach != nil {
		in, out := &in.NetworkMultiAttach, &out.NetworkMultiAttach
		*out = new(BpfNetworkMultiAttach)
		(*in).DeepCopyInto(*out)
	}
	if in.SingleAttach != nil {
		in, out := &in.SingleAttach, &out.SingleAttach
		*out = new(BpfSingleAttach)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BpfProgramAttachPoint.
func (in *BpfProgramAttachPoint) DeepCopy() *BpfProgramAttachPoint {
	if in == nil {
		return nil
	}
	out := new(BpfProgramAttachPoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BpfProgramConfig) DeepCopyInto(out *BpfProgramConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BpfProgramConfig.
func (in *BpfProgramConfig) DeepCopy() *BpfProgramConfig {
	if in == nil {
		return nil
	}
	out := new(BpfProgramConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BpfProgramConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BpfProgramConfigList) DeepCopyInto(out *BpfProgramConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BpfProgramConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BpfProgramConfigList.
func (in *BpfProgramConfigList) DeepCopy() *BpfProgramConfigList {
	if in == nil {
		return nil
	}
	out := new(BpfProgramConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BpfProgramConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BpfProgramConfigSpec) DeepCopyInto(out *BpfProgramConfigSpec) {
	*out = *in
	in.NodeSelector.DeepCopyInto(&out.NodeSelector)
	in.AttachPoint.DeepCopyInto(&out.AttachPoint)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BpfProgramConfigSpec.
func (in *BpfProgramConfigSpec) DeepCopy() *BpfProgramConfigSpec {
	if in == nil {
		return nil
	}
	out := new(BpfProgramConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BpfProgramConfigStatus) DeepCopyInto(out *BpfProgramConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BpfProgramConfigStatus.
func (in *BpfProgramConfigStatus) DeepCopy() *BpfProgramConfigStatus {
	if in == nil {
		return nil
	}
	out := new(BpfProgramConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BpfProgramList) DeepCopyInto(out *BpfProgramList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BpfProgram, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BpfProgramList.
func (in *BpfProgramList) DeepCopy() *BpfProgramList {
	if in == nil {
		return nil
	}
	out := new(BpfProgramList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BpfProgramList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BpfProgramMeta) DeepCopyInto(out *BpfProgramMeta) {
	*out = *in
	if in.AttachPoint != nil {
		in, out := &in.AttachPoint, &out.AttachPoint
		*out = new(BpfProgramAttachPoint)
		(*in).DeepCopyInto(*out)
	}
	if in.Maps != nil {
		in, out := &in.Maps, &out.Maps
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BpfProgramMeta.
func (in *BpfProgramMeta) DeepCopy() *BpfProgramMeta {
	if in == nil {
		return nil
	}
	out := new(BpfProgramMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BpfProgramSpec) DeepCopyInto(out *BpfProgramSpec) {
	*out = *in
	if in.Programs != nil {
		in, out := &in.Programs, &out.Programs
		*out = make(map[string]BpfProgramMeta, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BpfProgramSpec.
func (in *BpfProgramSpec) DeepCopy() *BpfProgramSpec {
	if in == nil {
		return nil
	}
	out := new(BpfProgramSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BpfProgramStatus) DeepCopyInto(out *BpfProgramStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BpfProgramStatus.
func (in *BpfProgramStatus) DeepCopy() *BpfProgramStatus {
	if in == nil {
		return nil
	}
	out := new(BpfProgramStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BpfSingleAttach) DeepCopyInto(out *BpfSingleAttach) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BpfSingleAttach.
func (in *BpfSingleAttach) DeepCopy() *BpfSingleAttach {
	if in == nil {
		return nil
	}
	out := new(BpfSingleAttach)
	in.DeepCopyInto(out)
	return out
}
