---
header:
  - license:
      content: |
        SPDX-License-Identifier: Apache-2.0
        Copyright Authors of bpfman
    paths:
      - bpfman
    paths-ignore:
      - "**/LICENSE-*"
      - "**/target/**"
      - "**/*.toml"
      - "**/*.proto"
      - "**/*.lock"
      - "**/*.yml"
      - "**/*.md"
      - bpfman/src/db/schema.rs
    comment: on-failure
  - license:
      content: |
        SPDX-License-Identifier: GPL-2.0-only
        Modifications Copyright Authors of bpfman
    paths:
      - bpf/xdp_dispatcher_v1.bpf.c
      - bpf/xdp_dispatcher_v2.bpf.c
      - examples/go-xdp-counter/bpf/xdp_counter.c
    comment: on-failure
  - license:
      content: |
        SPDX-License-Identifier: (GPL-2.0-only OR BSD-2-Clause)
        Copyright Authors of bpfman
    paths:
      - bpf/tc_dispatcher.bpf.c
      - examples/**/bpf/*.c
      - tests/**/*.bpf.c
    paths-ignore:
      - examples/go-xdp-counter/bpf/xdp_counter.c
    comment: on-failure
