---
extends: default
rules:
  line-length: disable
  document-start: disable
  comments:
    min-spaces-from-content: 1
  quoted-strings:
    required: only-when-needed
    quote-type: double
ignore:
  - libbpf/*
  - vendor/*
  - bpfman-operator/config/crd/*
  - bpfman-operator/config/rbac/*
  ## Kustomize automatically formats these incorrectly
  - bpfman-operator/config/bpfman-deployment/kustomization.yaml
  - bpfman-operator/config/bpfman-operator-deployment/kustomization.yaml
