[project]
dependencies = [
    "mike>=2.1.3",
    "mkdocs-callouts>=1.14.1",
    "mkdocs-material>=9.5.46",
    "mkdocs>=1.6.1",
]
description = "bpfman documentation pages"
name = "bpfman-docs"
readme = "README.md"
requires-python = ">=3.13"
version = "0.1.0"
