#!/usr/bin/env bash

sudo RUST_LOG=debug USE_SQLITE=1 ./target/debug/bpfman \
     load file \
     --path ~/src/github.com/frobware/bpfman-hacks/stats/bpf/stats-v2.o \
     --programs tracepoint:count_context_switches
