// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.15.8
// source: bpfd.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BytecodeImage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url             string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	ImagePullPolicy int32  `protobuf:"varint,2,opt,name=image_pull_policy,json=imagePullPolicy,proto3" json:"image_pull_policy,omitempty"`
	Username        string `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password        string `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *BytecodeImage) Reset() {
	*x = BytecodeImage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bpfd_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BytecodeImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BytecodeImage) ProtoMessage() {}

func (x *BytecodeImage) ProtoReflect() protoreflect.Message {
	mi := &file_bpfd_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BytecodeImage.ProtoReflect.Descriptor instead.
func (*BytecodeImage) Descriptor() ([]byte, []int) {
	return file_bpfd_proto_rawDescGZIP(), []int{0}
}

func (x *BytecodeImage) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *BytecodeImage) GetImagePullPolicy() int32 {
	if x != nil {
		return x.ImagePullPolicy
	}
	return 0
}

func (x *BytecodeImage) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *BytecodeImage) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type NoLocation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NoLocation) Reset() {
	*x = NoLocation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bpfd_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NoLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoLocation) ProtoMessage() {}

func (x *NoLocation) ProtoReflect() protoreflect.Message {
	mi := &file_bpfd_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoLocation.ProtoReflect.Descriptor instead.
func (*NoLocation) Descriptor() ([]byte, []int) {
	return file_bpfd_proto_rawDescGZIP(), []int{1}
}

type LoadRequestCommon struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Location:
	//
	//	*LoadRequestCommon_Image
	//	*LoadRequestCommon_File
	Location    isLoadRequestCommon_Location `protobuf_oneof:"location"`
	SectionName string                       `protobuf:"bytes,3,opt,name=section_name,json=sectionName,proto3" json:"section_name,omitempty"`
	ProgramType int32                        `protobuf:"varint,4,opt,name=program_type,json=programType,proto3" json:"program_type,omitempty"`
	Id          *string                      `protobuf:"bytes,5,opt,name=id,proto3,oneof" json:"id,omitempty"`
	GlobalData  map[string][]byte            `protobuf:"bytes,6,rep,name=global_data,json=globalData,proto3" json:"global_data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *LoadRequestCommon) Reset() {
	*x = LoadRequestCommon{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bpfd_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadRequestCommon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadRequestCommon) ProtoMessage() {}

func (x *LoadRequestCommon) ProtoReflect() protoreflect.Message {
	mi := &file_bpfd_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadRequestCommon.ProtoReflect.Descriptor instead.
func (*LoadRequestCommon) Descriptor() ([]byte, []int) {
	return file_bpfd_proto_rawDescGZIP(), []int{2}
}

func (m *LoadRequestCommon) GetLocation() isLoadRequestCommon_Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (x *LoadRequestCommon) GetImage() *BytecodeImage {
	if x, ok := x.GetLocation().(*LoadRequestCommon_Image); ok {
		return x.Image
	}
	return nil
}

func (x *LoadRequestCommon) GetFile() string {
	if x, ok := x.GetLocation().(*LoadRequestCommon_File); ok {
		return x.File
	}
	return ""
}

func (x *LoadRequestCommon) GetSectionName() string {
	if x != nil {
		return x.SectionName
	}
	return ""
}

func (x *LoadRequestCommon) GetProgramType() int32 {
	if x != nil {
		return x.ProgramType
	}
	return 0
}

func (x *LoadRequestCommon) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *LoadRequestCommon) GetGlobalData() map[string][]byte {
	if x != nil {
		return x.GlobalData
	}
	return nil
}

type isLoadRequestCommon_Location interface {
	isLoadRequestCommon_Location()
}

type LoadRequestCommon_Image struct {
	Image *BytecodeImage `protobuf:"bytes,1,opt,name=image,proto3,oneof"`
}

type LoadRequestCommon_File struct {
	File string `protobuf:"bytes,2,opt,name=file,proto3,oneof"`
}

func (*LoadRequestCommon_Image) isLoadRequestCommon_Location() {}

func (*LoadRequestCommon_File) isLoadRequestCommon_Location() {}

type NoAttachInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NoAttachInfo) Reset() {
	*x = NoAttachInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bpfd_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NoAttachInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoAttachInfo) ProtoMessage() {}

func (x *NoAttachInfo) ProtoReflect() protoreflect.Message {
	mi := &file_bpfd_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoAttachInfo.ProtoReflect.Descriptor instead.
func (*NoAttachInfo) Descriptor() ([]byte, []int) {
	return file_bpfd_proto_rawDescGZIP(), []int{3}
}

type XDPAttachInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Priority  int32   `protobuf:"varint,1,opt,name=priority,proto3" json:"priority,omitempty"`
	Iface     string  `protobuf:"bytes,2,opt,name=iface,proto3" json:"iface,omitempty"`
	Position  int32   `protobuf:"varint,3,opt,name=position,proto3" json:"position,omitempty"`
	ProceedOn []int32 `protobuf:"varint,4,rep,packed,name=proceed_on,json=proceedOn,proto3" json:"proceed_on,omitempty"`
}

func (x *XDPAttachInfo) Reset() {
	*x = XDPAttachInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bpfd_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XDPAttachInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XDPAttachInfo) ProtoMessage() {}

func (x *XDPAttachInfo) ProtoReflect() protoreflect.Message {
	mi := &file_bpfd_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XDPAttachInfo.ProtoReflect.Descriptor instead.
func (*XDPAttachInfo) Descriptor() ([]byte, []int) {
	return file_bpfd_proto_rawDescGZIP(), []int{4}
}

func (x *XDPAttachInfo) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *XDPAttachInfo) GetIface() string {
	if x != nil {
		return x.Iface
	}
	return ""
}

func (x *XDPAttachInfo) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *XDPAttachInfo) GetProceedOn() []int32 {
	if x != nil {
		return x.ProceedOn
	}
	return nil
}

type TCAttachInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Priority  int32   `protobuf:"varint,1,opt,name=priority,proto3" json:"priority,omitempty"`
	Iface     string  `protobuf:"bytes,2,opt,name=iface,proto3" json:"iface,omitempty"`
	Position  int32   `protobuf:"varint,3,opt,name=position,proto3" json:"position,omitempty"`
	Direction string  `protobuf:"bytes,4,opt,name=direction,proto3" json:"direction,omitempty"`
	ProceedOn []int32 `protobuf:"varint,5,rep,packed,name=proceed_on,json=proceedOn,proto3" json:"proceed_on,omitempty"`
}

func (x *TCAttachInfo) Reset() {
	*x = TCAttachInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bpfd_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TCAttachInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TCAttachInfo) ProtoMessage() {}

func (x *TCAttachInfo) ProtoReflect() protoreflect.Message {
	mi := &file_bpfd_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TCAttachInfo.ProtoReflect.Descriptor instead.
func (*TCAttachInfo) Descriptor() ([]byte, []int) {
	return file_bpfd_proto_rawDescGZIP(), []int{5}
}

func (x *TCAttachInfo) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *TCAttachInfo) GetIface() string {
	if x != nil {
		return x.Iface
	}
	return ""
}

func (x *TCAttachInfo) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *TCAttachInfo) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *TCAttachInfo) GetProceedOn() []int32 {
	if x != nil {
		return x.ProceedOn
	}
	return nil
}

type TracepointAttachInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tracepoint string `protobuf:"bytes,1,opt,name=tracepoint,proto3" json:"tracepoint,omitempty"`
}

func (x *TracepointAttachInfo) Reset() {
	*x = TracepointAttachInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bpfd_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TracepointAttachInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TracepointAttachInfo) ProtoMessage() {}

func (x *TracepointAttachInfo) ProtoReflect() protoreflect.Message {
	mi := &file_bpfd_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TracepointAttachInfo.ProtoReflect.Descriptor instead.
func (*TracepointAttachInfo) Descriptor() ([]byte, []int) {
	return file_bpfd_proto_rawDescGZIP(), []int{6}
}

func (x *TracepointAttachInfo) GetTracepoint() string {
	if x != nil {
		return x.Tracepoint
	}
	return ""
}

type UprobeAttachInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FnName    *string `protobuf:"bytes,1,opt,name=fn_name,json=fnName,proto3,oneof" json:"fn_name,omitempty"`
	Offset    *uint64 `protobuf:"varint,2,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
	Target    string  `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	Pid       *int32  `protobuf:"varint,4,opt,name=pid,proto3,oneof" json:"pid,omitempty"`
	Namespace *string `protobuf:"bytes,5,opt,name=namespace,proto3,oneof" json:"namespace,omitempty"`
}

func (x *UprobeAttachInfo) Reset() {
	*x = UprobeAttachInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bpfd_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UprobeAttachInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UprobeAttachInfo) ProtoMessage() {}

func (x *UprobeAttachInfo) ProtoReflect() protoreflect.Message {
	mi := &file_bpfd_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UprobeAttachInfo.ProtoReflect.Descriptor instead.
func (*UprobeAttachInfo) Descriptor() ([]byte, []int) {
	return file_bpfd_proto_rawDescGZIP(), []int{7}
}

func (x *UprobeAttachInfo) GetFnName() string {
	if x != nil && x.FnName != nil {
		return *x.FnName
	}
	return ""
}

func (x *UprobeAttachInfo) GetOffset() uint64 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

func (x *UprobeAttachInfo) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *UprobeAttachInfo) GetPid() int32 {
	if x != nil && x.Pid != nil {
		return *x.Pid
	}
	return 0
}

func (x *UprobeAttachInfo) GetNamespace() string {
	if x != nil && x.Namespace != nil {
		return *x.Namespace
	}
	return ""
}

type LoadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Common *LoadRequestCommon `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	// Types that are assignable to AttachInfo:
	//
	//	*LoadRequest_XdpAttachInfo
	//	*LoadRequest_TcAttachInfo
	//	*LoadRequest_TracepointAttachInfo
	//	*LoadRequest_UprobeAttachInfo
	AttachInfo isLoadRequest_AttachInfo `protobuf_oneof:"attach_info"`
}

func (x *LoadRequest) Reset() {
	*x = LoadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bpfd_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadRequest) ProtoMessage() {}

func (x *LoadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bpfd_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadRequest.ProtoReflect.Descriptor instead.
func (*LoadRequest) Descriptor() ([]byte, []int) {
	return file_bpfd_proto_rawDescGZIP(), []int{8}
}

func (x *LoadRequest) GetCommon() *LoadRequestCommon {
	if x != nil {
		return x.Common
	}
	return nil
}

func (m *LoadRequest) GetAttachInfo() isLoadRequest_AttachInfo {
	if m != nil {
		return m.AttachInfo
	}
	return nil
}

func (x *LoadRequest) GetXdpAttachInfo() *XDPAttachInfo {
	if x, ok := x.GetAttachInfo().(*LoadRequest_XdpAttachInfo); ok {
		return x.XdpAttachInfo
	}
	return nil
}

func (x *LoadRequest) GetTcAttachInfo() *TCAttachInfo {
	if x, ok := x.GetAttachInfo().(*LoadRequest_TcAttachInfo); ok {
		return x.TcAttachInfo
	}
	return nil
}

func (x *LoadRequest) GetTracepointAttachInfo() *TracepointAttachInfo {
	if x, ok := x.GetAttachInfo().(*LoadRequest_TracepointAttachInfo); ok {
		return x.TracepointAttachInfo
	}
	return nil
}

func (x *LoadRequest) GetUprobeAttachInfo() *UprobeAttachInfo {
	if x, ok := x.GetAttachInfo().(*LoadRequest_UprobeAttachInfo); ok {
		return x.UprobeAttachInfo
	}
	return nil
}

type isLoadRequest_AttachInfo interface {
	isLoadRequest_AttachInfo()
}

type LoadRequest_XdpAttachInfo struct {
	XdpAttachInfo *XDPAttachInfo `protobuf:"bytes,2,opt,name=xdp_attach_info,json=xdpAttachInfo,proto3,oneof"`
}

type LoadRequest_TcAttachInfo struct {
	TcAttachInfo *TCAttachInfo `protobuf:"bytes,3,opt,name=tc_attach_info,json=tcAttachInfo,proto3,oneof"`
}

type LoadRequest_TracepointAttachInfo struct {
	TracepointAttachInfo *TracepointAttachInfo `protobuf:"bytes,4,opt,name=tracepoint_attach_info,json=tracepointAttachInfo,proto3,oneof"`
}

type LoadRequest_UprobeAttachInfo struct {
	UprobeAttachInfo *UprobeAttachInfo `protobuf:"bytes,5,opt,name=uprobe_attach_info,json=uprobeAttachInfo,proto3,oneof"`
}

func (*LoadRequest_XdpAttachInfo) isLoadRequest_AttachInfo() {}

func (*LoadRequest_TcAttachInfo) isLoadRequest_AttachInfo() {}

func (*LoadRequest_TracepointAttachInfo) isLoadRequest_AttachInfo() {}

func (*LoadRequest_UprobeAttachInfo) isLoadRequest_AttachInfo() {}

type LoadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *LoadResponse) Reset() {
	*x = LoadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bpfd_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadResponse) ProtoMessage() {}

func (x *LoadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bpfd_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadResponse.ProtoReflect.Descriptor instead.
func (*LoadResponse) Descriptor() ([]byte, []int) {
	return file_bpfd_proto_rawDescGZIP(), []int{9}
}

func (x *LoadResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UnloadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *UnloadRequest) Reset() {
	*x = UnloadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bpfd_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnloadRequest) ProtoMessage() {}

func (x *UnloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bpfd_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnloadRequest.ProtoReflect.Descriptor instead.
func (*UnloadRequest) Descriptor() ([]byte, []int) {
	return file_bpfd_proto_rawDescGZIP(), []int{10}
}

func (x *UnloadRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UnloadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UnloadResponse) Reset() {
	*x = UnloadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bpfd_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnloadResponse) ProtoMessage() {}

func (x *UnloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bpfd_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnloadResponse.ProtoReflect.Descriptor instead.
func (*UnloadResponse) Descriptor() ([]byte, []int) {
	return file_bpfd_proto_rawDescGZIP(), []int{11}
}

type ListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProgramType      *uint32 `protobuf:"varint,1,opt,name=program_type,json=programType,proto3,oneof" json:"program_type,omitempty"`
	BpfdProgramsOnly *bool   `protobuf:"varint,2,opt,name=bpfd_programs_only,json=bpfdProgramsOnly,proto3,oneof" json:"bpfd_programs_only,omitempty"`
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bpfd_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bpfd_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_bpfd_proto_rawDescGZIP(), []int{12}
}

func (x *ListRequest) GetProgramType() uint32 {
	if x != nil && x.ProgramType != nil {
		return *x.ProgramType
	}
	return 0
}

func (x *ListRequest) GetBpfdProgramsOnly() bool {
	if x != nil && x.BpfdProgramsOnly != nil {
		return *x.BpfdProgramsOnly
	}
	return false
}

type ListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*ListResponse_ListResult `protobuf:"bytes,23,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bpfd_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bpfd_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_bpfd_proto_rawDescGZIP(), []int{13}
}

func (x *ListResponse) GetResults() []*ListResponse_ListResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type ListResponse_ListResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   *string `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	Name string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are assignable to Location:
	//
	//	*ListResponse_ListResult_NoLocation
	//	*ListResponse_ListResult_Image
	//	*ListResponse_ListResult_File
	Location    isListResponse_ListResult_Location `protobuf_oneof:"location"`
	ProgramType uint32                             `protobuf:"varint,6,opt,name=program_type,json=programType,proto3" json:"program_type,omitempty"`
	// Types that are assignable to AttachInfo:
	//
	//	*ListResponse_ListResult_None
	//	*ListResponse_ListResult_XdpAttachInfo
	//	*ListResponse_ListResult_TcAttachInfo
	//	*ListResponse_ListResult_TracepointAttachInfo
	//	*ListResponse_ListResult_UprobeAttachInfo
	AttachInfo    isListResponse_ListResult_AttachInfo `protobuf_oneof:"attach_info"`
	BpfId         uint32                               `protobuf:"varint,12,opt,name=bpf_id,json=bpfId,proto3" json:"bpf_id,omitempty"`
	LoadedAt      string                               `protobuf:"bytes,13,opt,name=loaded_at,json=loadedAt,proto3" json:"loaded_at,omitempty"`
	Tag           string                               `protobuf:"bytes,14,opt,name=tag,proto3" json:"tag,omitempty"`
	GplCompatible bool                                 `protobuf:"varint,15,opt,name=gpl_compatible,json=gplCompatible,proto3" json:"gpl_compatible,omitempty"`
	MapIds        []uint32                             `protobuf:"varint,16,rep,packed,name=map_ids,json=mapIds,proto3" json:"map_ids,omitempty"`
	BtfId         uint32                               `protobuf:"varint,17,opt,name=btf_id,json=btfId,proto3" json:"btf_id,omitempty"`
	BytesXlated   uint32                               `protobuf:"varint,18,opt,name=bytes_xlated,json=bytesXlated,proto3" json:"bytes_xlated,omitempty"`
	Jited         bool                                 `protobuf:"varint,19,opt,name=jited,proto3" json:"jited,omitempty"`
	BytesJited    uint32                               `protobuf:"varint,20,opt,name=bytes_jited,json=bytesJited,proto3" json:"bytes_jited,omitempty"`
	BytesMemlock  uint32                               `protobuf:"varint,21,opt,name=bytes_memlock,json=bytesMemlock,proto3" json:"bytes_memlock,omitempty"`
	VerifiedInsns uint32                               `protobuf:"varint,22,opt,name=verified_insns,json=verifiedInsns,proto3" json:"verified_insns,omitempty"`
}

func (x *ListResponse_ListResult) Reset() {
	*x = ListResponse_ListResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bpfd_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListResponse_ListResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse_ListResult) ProtoMessage() {}

func (x *ListResponse_ListResult) ProtoReflect() protoreflect.Message {
	mi := &file_bpfd_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse_ListResult.ProtoReflect.Descriptor instead.
func (*ListResponse_ListResult) Descriptor() ([]byte, []int) {
	return file_bpfd_proto_rawDescGZIP(), []int{13, 0}
}

func (x *ListResponse_ListResult) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *ListResponse_ListResult) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (m *ListResponse_ListResult) GetLocation() isListResponse_ListResult_Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (x *ListResponse_ListResult) GetNoLocation() *NoLocation {
	if x, ok := x.GetLocation().(*ListResponse_ListResult_NoLocation); ok {
		return x.NoLocation
	}
	return nil
}

func (x *ListResponse_ListResult) GetImage() *BytecodeImage {
	if x, ok := x.GetLocation().(*ListResponse_ListResult_Image); ok {
		return x.Image
	}
	return nil
}

func (x *ListResponse_ListResult) GetFile() string {
	if x, ok := x.GetLocation().(*ListResponse_ListResult_File); ok {
		return x.File
	}
	return ""
}

func (x *ListResponse_ListResult) GetProgramType() uint32 {
	if x != nil {
		return x.ProgramType
	}
	return 0
}

func (m *ListResponse_ListResult) GetAttachInfo() isListResponse_ListResult_AttachInfo {
	if m != nil {
		return m.AttachInfo
	}
	return nil
}

func (x *ListResponse_ListResult) GetNone() *NoAttachInfo {
	if x, ok := x.GetAttachInfo().(*ListResponse_ListResult_None); ok {
		return x.None
	}
	return nil
}

func (x *ListResponse_ListResult) GetXdpAttachInfo() *XDPAttachInfo {
	if x, ok := x.GetAttachInfo().(*ListResponse_ListResult_XdpAttachInfo); ok {
		return x.XdpAttachInfo
	}
	return nil
}

func (x *ListResponse_ListResult) GetTcAttachInfo() *TCAttachInfo {
	if x, ok := x.GetAttachInfo().(*ListResponse_ListResult_TcAttachInfo); ok {
		return x.TcAttachInfo
	}
	return nil
}

func (x *ListResponse_ListResult) GetTracepointAttachInfo() *TracepointAttachInfo {
	if x, ok := x.GetAttachInfo().(*ListResponse_ListResult_TracepointAttachInfo); ok {
		return x.TracepointAttachInfo
	}
	return nil
}

func (x *ListResponse_ListResult) GetUprobeAttachInfo() *UprobeAttachInfo {
	if x, ok := x.GetAttachInfo().(*ListResponse_ListResult_UprobeAttachInfo); ok {
		return x.UprobeAttachInfo
	}
	return nil
}

func (x *ListResponse_ListResult) GetBpfId() uint32 {
	if x != nil {
		return x.BpfId
	}
	return 0
}

func (x *ListResponse_ListResult) GetLoadedAt() string {
	if x != nil {
		return x.LoadedAt
	}
	return ""
}

func (x *ListResponse_ListResult) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *ListResponse_ListResult) GetGplCompatible() bool {
	if x != nil {
		return x.GplCompatible
	}
	return false
}

func (x *ListResponse_ListResult) GetMapIds() []uint32 {
	if x != nil {
		return x.MapIds
	}
	return nil
}

func (x *ListResponse_ListResult) GetBtfId() uint32 {
	if x != nil {
		return x.BtfId
	}
	return 0
}

func (x *ListResponse_ListResult) GetBytesXlated() uint32 {
	if x != nil {
		return x.BytesXlated
	}
	return 0
}

func (x *ListResponse_ListResult) GetJited() bool {
	if x != nil {
		return x.Jited
	}
	return false
}

func (x *ListResponse_ListResult) GetBytesJited() uint32 {
	if x != nil {
		return x.BytesJited
	}
	return 0
}

func (x *ListResponse_ListResult) GetBytesMemlock() uint32 {
	if x != nil {
		return x.BytesMemlock
	}
	return 0
}

func (x *ListResponse_ListResult) GetVerifiedInsns() uint32 {
	if x != nil {
		return x.VerifiedInsns
	}
	return 0
}

type isListResponse_ListResult_Location interface {
	isListResponse_ListResult_Location()
}

type ListResponse_ListResult_NoLocation struct {
	NoLocation *NoLocation `protobuf:"bytes,3,opt,name=no_location,json=noLocation,proto3,oneof"`
}

type ListResponse_ListResult_Image struct {
	Image *BytecodeImage `protobuf:"bytes,4,opt,name=image,proto3,oneof"`
}

type ListResponse_ListResult_File struct {
	File string `protobuf:"bytes,5,opt,name=file,proto3,oneof"`
}

func (*ListResponse_ListResult_NoLocation) isListResponse_ListResult_Location() {}

func (*ListResponse_ListResult_Image) isListResponse_ListResult_Location() {}

func (*ListResponse_ListResult_File) isListResponse_ListResult_Location() {}

type isListResponse_ListResult_AttachInfo interface {
	isListResponse_ListResult_AttachInfo()
}

type ListResponse_ListResult_None struct {
	None *NoAttachInfo `protobuf:"bytes,7,opt,name=none,proto3,oneof"`
}

type ListResponse_ListResult_XdpAttachInfo struct {
	XdpAttachInfo *XDPAttachInfo `protobuf:"bytes,8,opt,name=xdp_attach_info,json=xdpAttachInfo,proto3,oneof"`
}

type ListResponse_ListResult_TcAttachInfo struct {
	TcAttachInfo *TCAttachInfo `protobuf:"bytes,9,opt,name=tc_attach_info,json=tcAttachInfo,proto3,oneof"`
}

type ListResponse_ListResult_TracepointAttachInfo struct {
	TracepointAttachInfo *TracepointAttachInfo `protobuf:"bytes,10,opt,name=tracepoint_attach_info,json=tracepointAttachInfo,proto3,oneof"`
}

type ListResponse_ListResult_UprobeAttachInfo struct {
	UprobeAttachInfo *UprobeAttachInfo `protobuf:"bytes,11,opt,name=uprobe_attach_info,json=uprobeAttachInfo,proto3,oneof"`
}

func (*ListResponse_ListResult_None) isListResponse_ListResult_AttachInfo() {}

func (*ListResponse_ListResult_XdpAttachInfo) isListResponse_ListResult_AttachInfo() {}

func (*ListResponse_ListResult_TcAttachInfo) isListResponse_ListResult_AttachInfo() {}

func (*ListResponse_ListResult_TracepointAttachInfo) isListResponse_ListResult_AttachInfo() {}

func (*ListResponse_ListResult_UprobeAttachInfo) isListResponse_ListResult_AttachInfo() {}

var File_bpfd_proto protoreflect.FileDescriptor

var file_bpfd_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x62, 0x70, 0x66, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x62, 0x70,
	0x66, 0x64, 0x2e, 0x76, 0x31, 0x22, 0x85, 0x01, 0x0a, 0x0d, 0x42, 0x79, 0x74, 0x65, 0x63, 0x6f,
	0x64, 0x65, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x2a, 0x0a, 0x11, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x5f, 0x70, 0x75, 0x6c, 0x6c, 0x5f, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x50, 0x75, 0x6c, 0x6c, 0x50,
	0x6f, 0x6c, 0x69, 0x63, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x0c, 0x0a,
	0x0a, 0x4e, 0x6f, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xd3, 0x02, 0x0a, 0x11,
	0x4c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x12, 0x2e, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x62, 0x70, 0x66, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x79, 0x74, 0x65, 0x63,
	0x6f, 0x64, 0x65, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67,
	0x65, 0x12, 0x14, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x72,
	0x6f, 0x67, 0x72, 0x61, 0x6d, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0b, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x12, 0x13, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x02, 0x69, 0x64, 0x88,
	0x01, 0x01, 0x12, 0x4b, 0x0a, 0x0b, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x5f, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x62, 0x70, 0x66, 0x64, 0x2e, 0x76,
	0x31, 0x2e, 0x4c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x43, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x0a, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x1a,
	0x3d, 0x0a, 0x0f, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x0a,
	0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x05, 0x0a, 0x03, 0x5f, 0x69,
	0x64, 0x22, 0x0e, 0x0a, 0x0c, 0x4e, 0x6f, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x49, 0x6e, 0x66,
	0x6f, 0x22, 0x7c, 0x0a, 0x0d, 0x58, 0x44, 0x50, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x69, 0x66, 0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69,
	0x66, 0x61, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x65, 0x64, 0x5f, 0x6f, 0x6e, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x05, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x65, 0x64, 0x4f, 0x6e, 0x22,
	0x99, 0x01, 0x0a, 0x0c, 0x54, 0x43, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x69, 0x66, 0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x66, 0x61,
	0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c,
	0x0a, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a,
	0x70, 0x72, 0x6f, 0x63, 0x65, 0x65, 0x64, 0x5f, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x03, 0x28, 0x05,
	0x52, 0x09, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x65, 0x64, 0x4f, 0x6e, 0x22, 0x36, 0x0a, 0x14, 0x54,
	0x72, 0x61, 0x63, 0x65, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x72, 0x61, 0x63, 0x65, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x72, 0x61, 0x63, 0x65, 0x70, 0x6f,
	0x69, 0x6e, 0x74, 0x22, 0xcc, 0x01, 0x0a, 0x10, 0x55, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x41, 0x74,
	0x74, 0x61, 0x63, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1c, 0x0a, 0x07, 0x66, 0x6e, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x66, 0x6e, 0x4e,
	0x61, 0x6d, 0x65, 0x88, 0x01, 0x01, 0x12, 0x1b, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x48, 0x01, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74,
	0x88, 0x01, 0x01, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x15, 0x0a, 0x03, 0x70,
	0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x48, 0x02, 0x52, 0x03, 0x70, 0x69, 0x64, 0x88,
	0x01, 0x01, 0x12, 0x21, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x03, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x88, 0x01, 0x01, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x66, 0x6e, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x42, 0x06, 0x0a, 0x04,
	0x5f, 0x70, 0x69, 0x64, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x22, 0xf3, 0x02, 0x0a, 0x0b, 0x4c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x32, 0x0a, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x62, 0x70, 0x66, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x6f, 0x61,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x06,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x12, 0x40, 0x0a, 0x0f, 0x78, 0x64, 0x70, 0x5f, 0x61, 0x74,
	0x74, 0x61, 0x63, 0x68, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x62, 0x70, 0x66, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x58, 0x44, 0x50, 0x41, 0x74, 0x74,
	0x61, 0x63, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x48, 0x00, 0x52, 0x0d, 0x78, 0x64, 0x70, 0x41, 0x74,
	0x74, 0x61, 0x63, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x3d, 0x0a, 0x0e, 0x74, 0x63, 0x5f, 0x61,
	0x74, 0x74, 0x61, 0x63, 0x68, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x62, 0x70, 0x66, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x43, 0x41, 0x74, 0x74,
	0x61, 0x63, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x48, 0x00, 0x52, 0x0c, 0x74, 0x63, 0x41, 0x74, 0x74,
	0x61, 0x63, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x55, 0x0a, 0x16, 0x74, 0x72, 0x61, 0x63, 0x65,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x5f, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x5f, 0x69, 0x6e, 0x66,
	0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x62, 0x70, 0x66, 0x64, 0x2e, 0x76,
	0x31, 0x2e, 0x54, 0x72, 0x61, 0x63, 0x65, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x41, 0x74, 0x74, 0x61,
	0x63, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x48, 0x00, 0x52, 0x14, 0x74, 0x72, 0x61, 0x63, 0x65, 0x70,
	0x6f, 0x69, 0x6e, 0x74, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x49,
	0x0a, 0x12, 0x75, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x5f, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x5f,
	0x69, 0x6e, 0x66, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x62, 0x70, 0x66,
	0x64, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x41, 0x74, 0x74, 0x61, 0x63,
	0x68, 0x49, 0x6e, 0x66, 0x6f, 0x48, 0x00, 0x52, 0x10, 0x75, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x41,
	0x74, 0x74, 0x61, 0x63, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x0d, 0x0a, 0x0b, 0x61, 0x74, 0x74,
	0x61, 0x63, 0x68, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x1e, 0x0a, 0x0c, 0x4c, 0x6f, 0x61, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x1f, 0x0a, 0x0d, 0x55, 0x6e, 0x6c, 0x6f,
	0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x10, 0x0a, 0x0e, 0x55, 0x6e, 0x6c,
	0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x90, 0x01, 0x0a, 0x0b,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x0c, 0x70,
	0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x48, 0x00, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x54, 0x79, 0x70, 0x65,
	0x88, 0x01, 0x01, 0x12, 0x31, 0x0a, 0x12, 0x62, 0x70, 0x66, 0x64, 0x5f, 0x70, 0x72, 0x6f, 0x67,
	0x72, 0x61, 0x6d, 0x73, 0x5f, 0x6f, 0x6e, 0x6c, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x48,
	0x01, 0x52, 0x10, 0x62, 0x70, 0x66, 0x64, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x73, 0x4f,
	0x6e, 0x6c, 0x79, 0x88, 0x01, 0x01, 0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x70, 0x72, 0x6f, 0x67, 0x72,
	0x61, 0x6d, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x42, 0x15, 0x0a, 0x13, 0x5f, 0x62, 0x70, 0x66, 0x64,
	0x5f, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x73, 0x5f, 0x6f, 0x6e, 0x6c, 0x79, 0x22, 0xd8,
	0x07, 0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x3a, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x17, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x20, 0x2e, 0x62, 0x70, 0x66, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x1a, 0x8b, 0x07, 0x0a, 0x0a,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x13, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x02, 0x69, 0x64, 0x88, 0x01, 0x01, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x36, 0x0a, 0x0b, 0x6e, 0x6f, 0x5f, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x62, 0x70, 0x66, 0x64, 0x2e,
	0x76, 0x31, 0x2e, 0x4e, 0x6f, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52,
	0x0a, 0x6e, 0x6f, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2e, 0x0a, 0x05, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x62, 0x70, 0x66,
	0x64, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x79, 0x74, 0x65, 0x63, 0x6f, 0x64, 0x65, 0x49, 0x6d, 0x61,
	0x67, 0x65, 0x48, 0x00, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x04, 0x66,
	0x69, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x66, 0x69, 0x6c,
	0x65, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x2b, 0x0a, 0x04, 0x6e, 0x6f, 0x6e, 0x65, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x62, 0x70, 0x66, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x6f, 0x41,
	0x74, 0x74, 0x61, 0x63, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x48, 0x01, 0x52, 0x04, 0x6e, 0x6f, 0x6e,
	0x65, 0x12, 0x40, 0x0a, 0x0f, 0x78, 0x64, 0x70, 0x5f, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x5f,
	0x69, 0x6e, 0x66, 0x6f, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x62, 0x70, 0x66,
	0x64, 0x2e, 0x76, 0x31, 0x2e, 0x58, 0x44, 0x50, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x49, 0x6e,
	0x66, 0x6f, 0x48, 0x01, 0x52, 0x0d, 0x78, 0x64, 0x70, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x3d, 0x0a, 0x0e, 0x74, 0x63, 0x5f, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68,
	0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x62, 0x70,
	0x66, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x43, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x49, 0x6e,
	0x66, 0x6f, 0x48, 0x01, 0x52, 0x0c, 0x74, 0x63, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x55, 0x0a, 0x16, 0x74, 0x72, 0x61, 0x63, 0x65, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x5f, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x62, 0x70, 0x66, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x72, 0x61,
	0x63, 0x65, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x49, 0x6e, 0x66,
	0x6f, 0x48, 0x01, 0x52, 0x14, 0x74, 0x72, 0x61, 0x63, 0x65, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x41,
	0x74, 0x74, 0x61, 0x63, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x49, 0x0a, 0x12, 0x75, 0x70, 0x72,
	0x6f, 0x62, 0x65, 0x5f, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18,
	0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x62, 0x70, 0x66, 0x64, 0x2e, 0x76, 0x31, 0x2e,
	0x55, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x49, 0x6e, 0x66, 0x6f,
	0x48, 0x01, 0x52, 0x10, 0x75, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x15, 0x0a, 0x06, 0x62, 0x70, 0x66, 0x5f, 0x69, 0x64, 0x18, 0x0c,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x62, 0x70, 0x66, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x6c,
	0x6f, 0x61, 0x64, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x41, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18,
	0x0e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x61, 0x67, 0x12, 0x25, 0x0a, 0x0e, 0x67, 0x70,
	0x6c, 0x5f, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x74, 0x69, 0x62, 0x6c, 0x65, 0x18, 0x0f, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0d, 0x67, 0x70, 0x6c, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x74, 0x69, 0x62, 0x6c,
	0x65, 0x12, 0x17, 0x0a, 0x07, 0x6d, 0x61, 0x70, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x10, 0x20, 0x03,
	0x28, 0x0d, 0x52, 0x06, 0x6d, 0x61, 0x70, 0x49, 0x64, 0x73, 0x12, 0x15, 0x0a, 0x06, 0x62, 0x74,
	0x66, 0x5f, 0x69, 0x64, 0x18, 0x11, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x62, 0x74, 0x66, 0x49,
	0x64, 0x12, 0x21, 0x0a, 0x0c, 0x62, 0x79, 0x74, 0x65, 0x73, 0x5f, 0x78, 0x6c, 0x61, 0x74, 0x65,
	0x64, 0x18, 0x12, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x62, 0x79, 0x74, 0x65, 0x73, 0x58, 0x6c,
	0x61, 0x74, 0x65, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6a, 0x69, 0x74, 0x65, 0x64, 0x18, 0x13, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x05, 0x6a, 0x69, 0x74, 0x65, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x62, 0x79,
	0x74, 0x65, 0x73, 0x5f, 0x6a, 0x69, 0x74, 0x65, 0x64, 0x18, 0x14, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x0a, 0x62, 0x79, 0x74, 0x65, 0x73, 0x4a, 0x69, 0x74, 0x65, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x62,
	0x79, 0x74, 0x65, 0x73, 0x5f, 0x6d, 0x65, 0x6d, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x15, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0c, 0x62, 0x79, 0x74, 0x65, 0x73, 0x4d, 0x65, 0x6d, 0x6c, 0x6f, 0x63, 0x6b,
	0x12, 0x25, 0x0a, 0x0e, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x5f, 0x69, 0x6e, 0x73,
	0x6e, 0x73, 0x18, 0x16, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69,
	0x65, 0x64, 0x49, 0x6e, 0x73, 0x6e, 0x73, 0x42, 0x0a, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x42, 0x0d, 0x0a, 0x0b, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x5f, 0x69, 0x6e,
	0x66, 0x6f, 0x42, 0x05, 0x0a, 0x03, 0x5f, 0x69, 0x64, 0x32, 0xad, 0x01, 0x0a, 0x06, 0x4c, 0x6f,
	0x61, 0x64, 0x65, 0x72, 0x12, 0x33, 0x0a, 0x04, 0x4c, 0x6f, 0x61, 0x64, 0x12, 0x14, 0x2e, 0x62,
	0x70, 0x66, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x15, 0x2e, 0x62, 0x70, 0x66, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x6f, 0x61,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x06, 0x55, 0x6e, 0x6c,
	0x6f, 0x61, 0x64, 0x12, 0x16, 0x2e, 0x62, 0x70, 0x66, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x6e,
	0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x62, 0x70,
	0x66, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x2e, 0x62,
	0x70, 0x66, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x15, 0x2e, 0x62, 0x70, 0x66, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x70, 0x66, 0x64, 0x2d, 0x64, 0x65, 0x76,
	0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x67, 0x6f, 0x62, 0x70, 0x66, 0x64, 0x2f,
	0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bpfd_proto_rawDescOnce sync.Once
	file_bpfd_proto_rawDescData = file_bpfd_proto_rawDesc
)

func file_bpfd_proto_rawDescGZIP() []byte {
	file_bpfd_proto_rawDescOnce.Do(func() {
		file_bpfd_proto_rawDescData = protoimpl.X.CompressGZIP(file_bpfd_proto_rawDescData)
	})
	return file_bpfd_proto_rawDescData
}

var file_bpfd_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_bpfd_proto_goTypes = []interface{}{
	(*BytecodeImage)(nil),           // 0: bpfd.v1.BytecodeImage
	(*NoLocation)(nil),              // 1: bpfd.v1.NoLocation
	(*LoadRequestCommon)(nil),       // 2: bpfd.v1.LoadRequestCommon
	(*NoAttachInfo)(nil),            // 3: bpfd.v1.NoAttachInfo
	(*XDPAttachInfo)(nil),           // 4: bpfd.v1.XDPAttachInfo
	(*TCAttachInfo)(nil),            // 5: bpfd.v1.TCAttachInfo
	(*TracepointAttachInfo)(nil),    // 6: bpfd.v1.TracepointAttachInfo
	(*UprobeAttachInfo)(nil),        // 7: bpfd.v1.UprobeAttachInfo
	(*LoadRequest)(nil),             // 8: bpfd.v1.LoadRequest
	(*LoadResponse)(nil),            // 9: bpfd.v1.LoadResponse
	(*UnloadRequest)(nil),           // 10: bpfd.v1.UnloadRequest
	(*UnloadResponse)(nil),          // 11: bpfd.v1.UnloadResponse
	(*ListRequest)(nil),             // 12: bpfd.v1.ListRequest
	(*ListResponse)(nil),            // 13: bpfd.v1.ListResponse
	nil,                             // 14: bpfd.v1.LoadRequestCommon.GlobalDataEntry
	(*ListResponse_ListResult)(nil), // 15: bpfd.v1.ListResponse.ListResult
}
var file_bpfd_proto_depIdxs = []int32{
	0,  // 0: bpfd.v1.LoadRequestCommon.image:type_name -> bpfd.v1.BytecodeImage
	14, // 1: bpfd.v1.LoadRequestCommon.global_data:type_name -> bpfd.v1.LoadRequestCommon.GlobalDataEntry
	2,  // 2: bpfd.v1.LoadRequest.common:type_name -> bpfd.v1.LoadRequestCommon
	4,  // 3: bpfd.v1.LoadRequest.xdp_attach_info:type_name -> bpfd.v1.XDPAttachInfo
	5,  // 4: bpfd.v1.LoadRequest.tc_attach_info:type_name -> bpfd.v1.TCAttachInfo
	6,  // 5: bpfd.v1.LoadRequest.tracepoint_attach_info:type_name -> bpfd.v1.TracepointAttachInfo
	7,  // 6: bpfd.v1.LoadRequest.uprobe_attach_info:type_name -> bpfd.v1.UprobeAttachInfo
	15, // 7: bpfd.v1.ListResponse.results:type_name -> bpfd.v1.ListResponse.ListResult
	1,  // 8: bpfd.v1.ListResponse.ListResult.no_location:type_name -> bpfd.v1.NoLocation
	0,  // 9: bpfd.v1.ListResponse.ListResult.image:type_name -> bpfd.v1.BytecodeImage
	3,  // 10: bpfd.v1.ListResponse.ListResult.none:type_name -> bpfd.v1.NoAttachInfo
	4,  // 11: bpfd.v1.ListResponse.ListResult.xdp_attach_info:type_name -> bpfd.v1.XDPAttachInfo
	5,  // 12: bpfd.v1.ListResponse.ListResult.tc_attach_info:type_name -> bpfd.v1.TCAttachInfo
	6,  // 13: bpfd.v1.ListResponse.ListResult.tracepoint_attach_info:type_name -> bpfd.v1.TracepointAttachInfo
	7,  // 14: bpfd.v1.ListResponse.ListResult.uprobe_attach_info:type_name -> bpfd.v1.UprobeAttachInfo
	8,  // 15: bpfd.v1.Loader.Load:input_type -> bpfd.v1.LoadRequest
	10, // 16: bpfd.v1.Loader.Unload:input_type -> bpfd.v1.UnloadRequest
	12, // 17: bpfd.v1.Loader.List:input_type -> bpfd.v1.ListRequest
	9,  // 18: bpfd.v1.Loader.Load:output_type -> bpfd.v1.LoadResponse
	11, // 19: bpfd.v1.Loader.Unload:output_type -> bpfd.v1.UnloadResponse
	13, // 20: bpfd.v1.Loader.List:output_type -> bpfd.v1.ListResponse
	18, // [18:21] is the sub-list for method output_type
	15, // [15:18] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_bpfd_proto_init() }
func file_bpfd_proto_init() {
	if File_bpfd_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bpfd_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BytecodeImage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bpfd_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NoLocation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bpfd_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoadRequestCommon); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bpfd_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NoAttachInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bpfd_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XDPAttachInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bpfd_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TCAttachInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bpfd_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TracepointAttachInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bpfd_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UprobeAttachInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bpfd_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bpfd_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bpfd_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnloadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bpfd_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnloadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bpfd_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bpfd_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bpfd_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListResponse_ListResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_bpfd_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*LoadRequestCommon_Image)(nil),
		(*LoadRequestCommon_File)(nil),
	}
	file_bpfd_proto_msgTypes[7].OneofWrappers = []interface{}{}
	file_bpfd_proto_msgTypes[8].OneofWrappers = []interface{}{
		(*LoadRequest_XdpAttachInfo)(nil),
		(*LoadRequest_TcAttachInfo)(nil),
		(*LoadRequest_TracepointAttachInfo)(nil),
		(*LoadRequest_UprobeAttachInfo)(nil),
	}
	file_bpfd_proto_msgTypes[12].OneofWrappers = []interface{}{}
	file_bpfd_proto_msgTypes[15].OneofWrappers = []interface{}{
		(*ListResponse_ListResult_NoLocation)(nil),
		(*ListResponse_ListResult_Image)(nil),
		(*ListResponse_ListResult_File)(nil),
		(*ListResponse_ListResult_None)(nil),
		(*ListResponse_ListResult_XdpAttachInfo)(nil),
		(*ListResponse_ListResult_TcAttachInfo)(nil),
		(*ListResponse_ListResult_TracepointAttachInfo)(nil),
		(*ListResponse_ListResult_UprobeAttachInfo)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bpfd_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bpfd_proto_goTypes,
		DependencyIndexes: file_bpfd_proto_depIdxs,
		MessageInfos:      file_bpfd_proto_msgTypes,
	}.Build()
	File_bpfd_proto = out.File
	file_bpfd_proto_rawDesc = nil
	file_bpfd_proto_goTypes = nil
	file_bpfd_proto_depIdxs = nil
}
