FROM golang:1.19 as go-tc-counter-build

RUN apt-get update && apt-get install -y \
 clang \
 gcc-multilib \
 libbpf-dev

RUN go install github.com/cilium/ebpf/cmd/bpf2go@master

WORKDIR /usr/src/bpfd/
COPY ./ /usr/src/bpfd/

WORKDIR /usr/src/bpfd/examples/go-tc-counter

# Compile go-tc-counter
RUN go generate
RUN go build

FROM registry.fedoraproject.org/fedora-minimal:latest

COPY --from=go-tc-counter-build  /usr/src/bpfd/examples/go-tc-counter/go-tc-counter .

ENTRYPOINT ["./go-tc-counter"]
