/*
Copyright 2023 The bpfman Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/bpfman/bpfman/bpfman-operator/apis/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeBpfPrograms implements BpfProgramInterface
type FakeBpfPrograms struct {
	Fake *FakeBpfmanV1alpha1
}

var bpfprogramsResource = schema.GroupVersionResource{Group: "bpfman.io", Version: "v1alpha1", Resource: "bpfprograms"}

var bpfprogramsKind = schema.GroupVersionKind{Group: "bpfman.io", Version: "v1alpha1", Kind: "BpfProgram"}

// Get takes name of the bpfProgram, and returns the corresponding bpfProgram object, and an error if there is any.
func (c *FakeBpfPrograms) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.BpfProgram, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(bpfprogramsResource, name), &v1alpha1.BpfProgram{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BpfProgram), err
}

// List takes label and field selectors, and returns the list of BpfPrograms that match those selectors.
func (c *FakeBpfPrograms) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.BpfProgramList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(bpfprogramsResource, bpfprogramsKind, opts), &v1alpha1.BpfProgramList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.BpfProgramList{ListMeta: obj.(*v1alpha1.BpfProgramList).ListMeta}
	for _, item := range obj.(*v1alpha1.BpfProgramList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested bpfPrograms.
func (c *FakeBpfPrograms) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(bpfprogramsResource, opts))
}

// Create takes the representation of a bpfProgram and creates it.  Returns the server's representation of the bpfProgram, and an error, if there is any.
func (c *FakeBpfPrograms) Create(ctx context.Context, bpfProgram *v1alpha1.BpfProgram, opts v1.CreateOptions) (result *v1alpha1.BpfProgram, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(bpfprogramsResource, bpfProgram), &v1alpha1.BpfProgram{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BpfProgram), err
}

// Update takes the representation of a bpfProgram and updates it. Returns the server's representation of the bpfProgram, and an error, if there is any.
func (c *FakeBpfPrograms) Update(ctx context.Context, bpfProgram *v1alpha1.BpfProgram, opts v1.UpdateOptions) (result *v1alpha1.BpfProgram, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(bpfprogramsResource, bpfProgram), &v1alpha1.BpfProgram{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BpfProgram), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeBpfPrograms) UpdateStatus(ctx context.Context, bpfProgram *v1alpha1.BpfProgram, opts v1.UpdateOptions) (*v1alpha1.BpfProgram, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(bpfprogramsResource, "status", bpfProgram), &v1alpha1.BpfProgram{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BpfProgram), err
}

// Delete takes name of the bpfProgram and deletes it. Returns an error if one occurs.
func (c *FakeBpfPrograms) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(bpfprogramsResource, name, opts), &v1alpha1.BpfProgram{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeBpfPrograms) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(bpfprogramsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.BpfProgramList{})
	return err
}

// Patch applies the patch and returns the patched bpfProgram.
func (c *FakeBpfPrograms) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.BpfProgram, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(bpfprogramsResource, name, pt, data, subresources...), &v1alpha1.BpfProgram{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BpfProgram), err
}
