/*
Copyright 2023 The bpfman Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/bpfman/bpfman/bpfman-operator/apis/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeFentryPrograms implements FentryProgramInterface
type FakeFentryPrograms struct {
	Fake *FakeBpfmanV1alpha1
}

var fentryprogramsResource = schema.GroupVersionResource{Group: "bpfman.io", Version: "v1alpha1", Resource: "fentryprograms"}

var fentryprogramsKind = schema.GroupVersionKind{Group: "bpfman.io", Version: "v1alpha1", Kind: "FentryProgram"}

// Get takes name of the fentryProgram, and returns the corresponding fentryProgram object, and an error if there is any.
func (c *FakeFentryPrograms) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.FentryProgram, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(fentryprogramsResource, name), &v1alpha1.FentryProgram{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FentryProgram), err
}

// List takes label and field selectors, and returns the list of FentryPrograms that match those selectors.
func (c *FakeFentryPrograms) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.FentryProgramList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(fentryprogramsResource, fentryprogramsKind, opts), &v1alpha1.FentryProgramList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.FentryProgramList{ListMeta: obj.(*v1alpha1.FentryProgramList).ListMeta}
	for _, item := range obj.(*v1alpha1.FentryProgramList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested fentryPrograms.
func (c *FakeFentryPrograms) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(fentryprogramsResource, opts))
}

// Create takes the representation of a fentryProgram and creates it.  Returns the server's representation of the fentryProgram, and an error, if there is any.
func (c *FakeFentryPrograms) Create(ctx context.Context, fentryProgram *v1alpha1.FentryProgram, opts v1.CreateOptions) (result *v1alpha1.FentryProgram, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(fentryprogramsResource, fentryProgram), &v1alpha1.FentryProgram{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FentryProgram), err
}

// Update takes the representation of a fentryProgram and updates it. Returns the server's representation of the fentryProgram, and an error, if there is any.
func (c *FakeFentryPrograms) Update(ctx context.Context, fentryProgram *v1alpha1.FentryProgram, opts v1.UpdateOptions) (result *v1alpha1.FentryProgram, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(fentryprogramsResource, fentryProgram), &v1alpha1.FentryProgram{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FentryProgram), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeFentryPrograms) UpdateStatus(ctx context.Context, fentryProgram *v1alpha1.FentryProgram, opts v1.UpdateOptions) (*v1alpha1.FentryProgram, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(fentryprogramsResource, "status", fentryProgram), &v1alpha1.FentryProgram{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FentryProgram), err
}

// Delete takes name of the fentryProgram and deletes it. Returns an error if one occurs.
func (c *FakeFentryPrograms) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(fentryprogramsResource, name, opts), &v1alpha1.FentryProgram{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeFentryPrograms) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(fentryprogramsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.FentryProgramList{})
	return err
}

// Patch applies the patch and returns the patched fentryProgram.
func (c *FakeFentryPrograms) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.FentryProgram, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(fentryprogramsResource, name, pt, data, subresources...), &v1alpha1.FentryProgram{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FentryProgram), err
}
