/*
Copyright 2023 The bpfman Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/bpfman/bpfman/bpfman-operator/apis/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeKprobePrograms implements KprobeProgramInterface
type FakeKprobePrograms struct {
	Fake *FakeBpfmanV1alpha1
}

var kprobeprogramsResource = schema.GroupVersionResource{Group: "bpfman.io", Version: "v1alpha1", Resource: "kprobeprograms"}

var kprobeprogramsKind = schema.GroupVersionKind{Group: "bpfman.io", Version: "v1alpha1", Kind: "KprobeProgram"}

// Get takes name of the kprobeProgram, and returns the corresponding kprobeProgram object, and an error if there is any.
func (c *FakeKprobePrograms) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.KprobeProgram, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(kprobeprogramsResource, name), &v1alpha1.KprobeProgram{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KprobeProgram), err
}

// List takes label and field selectors, and returns the list of KprobePrograms that match those selectors.
func (c *FakeKprobePrograms) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.KprobeProgramList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(kprobeprogramsResource, kprobeprogramsKind, opts), &v1alpha1.KprobeProgramList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.KprobeProgramList{ListMeta: obj.(*v1alpha1.KprobeProgramList).ListMeta}
	for _, item := range obj.(*v1alpha1.KprobeProgramList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested kprobePrograms.
func (c *FakeKprobePrograms) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(kprobeprogramsResource, opts))
}

// Create takes the representation of a kprobeProgram and creates it.  Returns the server's representation of the kprobeProgram, and an error, if there is any.
func (c *FakeKprobePrograms) Create(ctx context.Context, kprobeProgram *v1alpha1.KprobeProgram, opts v1.CreateOptions) (result *v1alpha1.KprobeProgram, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(kprobeprogramsResource, kprobeProgram), &v1alpha1.KprobeProgram{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KprobeProgram), err
}

// Update takes the representation of a kprobeProgram and updates it. Returns the server's representation of the kprobeProgram, and an error, if there is any.
func (c *FakeKprobePrograms) Update(ctx context.Context, kprobeProgram *v1alpha1.KprobeProgram, opts v1.UpdateOptions) (result *v1alpha1.KprobeProgram, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(kprobeprogramsResource, kprobeProgram), &v1alpha1.KprobeProgram{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KprobeProgram), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeKprobePrograms) UpdateStatus(ctx context.Context, kprobeProgram *v1alpha1.KprobeProgram, opts v1.UpdateOptions) (*v1alpha1.KprobeProgram, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(kprobeprogramsResource, "status", kprobeProgram), &v1alpha1.KprobeProgram{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KprobeProgram), err
}

// Delete takes name of the kprobeProgram and deletes it. Returns an error if one occurs.
func (c *FakeKprobePrograms) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(kprobeprogramsResource, name, opts), &v1alpha1.KprobeProgram{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeKprobePrograms) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(kprobeprogramsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.KprobeProgramList{})
	return err
}

// Patch applies the patch and returns the patched kprobeProgram.
func (c *FakeKprobePrograms) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.KprobeProgram, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(kprobeprogramsResource, name, pt, data, subresources...), &v1alpha1.KprobeProgram{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KprobeProgram), err
}
