# Build the manager binary
FROM golang:1.19 as bpfd-agent-build
ARG TARGETOS
ARG TARGETARCH

WORKDIR /usr/src/bpfd/

# Copy the Go Modules manifests
COPY ./bpfd-operator/go.mod bpfd-operator/go.mod
COPY ./bpfd-operator/go.sum bpfd-operator/go.sum

# cache deps before building and copying source so that we don't need to re-download as much
# and so that source changes don't invalidate our downloaded layer
RUN cd bpfd-operator && go mod download

# Copy the go source
COPY ./bpfd-operator/cmd/bpfd-agent/main.go bpfd-operator/main.go
COPY ./bpfd-operator/apis/ bpfd-operator/apis/
COPY ./bpfd-operator/controllers/ bpfd-operator/controllers/
COPY ./bpfd-operator/internal/ bpfd-operator/internal/

# Copy local version of gobpfd bindings and go work sum so 
# that local bpfd API changes can get propogated to the container builds
# TODO(astoycos) When the bpfd-operator is split into it's own REPO this will
# get slimmed down
COPY ./go.work go.work
COPY ./go.work.sum go.work.sum 
COPY ./clients/gobpfd ./clients/gobpfd
COPY ./examples examples

# Build
# the GOARCH has not a default value to allow the binary be built according to the host where the command
# was called. For example, if we call make docker-build in a local env which has the Apple Silicon M1 SO
# the docker BUILDPLATFORM arg will be linux/arm64 when for Apple x86 it will be linux/amd64. Therefore,
# by leaving it empty we can ensure that the container and binary shipped on it will have the same platform.
RUN cd bpfd-operator && CGO_ENABLED=0 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} go build -a -o bpfd-agent main.go

# Use distroless as minimal base image to package the manager binary
# Refer to https://github.com/GoogleContainerTools/distroless for more details
# Uncomment for debug build
# FROM gcr.io/distroless/static:debug

FROM gcr.io/distroless/static:nonroot
WORKDIR /
COPY --from=bpfd-agent-build /usr/src/bpfd/bpfd-operator/bpfd-agent .
USER 65532:65532

ENTRYPOINT ["/bpfd-agent"]