package residue

import (
	"errors"
	"fmt"
	"io/fs"
	"os"
	"regexp"

	"github.com/vishvananda/netlink"

	"github.com/bpfman/bpfman/internal/testnetroute"
)

// DefaultNetnsDir is the iproute2 convention for named network
// namespaces. iproute2's `ip netns` family and the vendored
// vishvananda/netns library both hardcode this path internally,
// so production callers should pass DefaultNetnsDir; the netnsDir
// parameter on the API exists for test isolation only.
const DefaultNetnsDir = "/run/netns"

// StaleTestIfaceRe matches interface and namespace names
// generated by the e2e harness's uniqueTestName: "B", 12 hex
// characters, "N", optionally with an "a" or "b" veth suffix.
// Exported so callers can use the same naming convention when
// they only need the regex, not the full sweep.
var StaleTestIfaceRe = regexp.MustCompile(`^B[0-9a-f]{12}N[ab]?$`)

// ScanE2EResidue returns a Plan that removes residue
// attributable to the e2e harness: bpf_link pins attached to
// test-named interfaces (so the kernel does not leave detached
// link objects behind once the netdevs disappear), host
// interfaces matching StaleTestIfaceRe, and named netns under
// netnsDir matching the same regex. The plan is ordered: pins
// first, then interfaces, then netns.
//
// bpffsRoot is the bpf fs mount point used to find XDP pin
// paths (DefaultBPFFS for the system default); netnsDir is the
// directory where named netns are mounted (DefaultNetnsDir for
// the iproute2 default).
func ScanE2EResidue(bpffsRoot, netnsDir string) (Plan, error) {
	var plan Plan

	pins, err := findLinkPinsOnTestInterfaces(bpffsRoot, netnsDir)
	if err != nil {
		return plan, fmt.Errorf("scan link pins on test interfaces: %w", err)
	}
	for _, pin := range pins {
		plan = append(plan, RemovePin{Path: pin})
	}

	// Programs the e2e scripts load out-of-band via bpftool are pinned
	// on the system bpffs under E2EUnmanagedPinPrefix; the link-pin scan
	// above skips them (they are program pins, not links). Reclaim any
	// left behind by a script that aborted before its rm defer ran.
	progPins, err := findE2EUnmanagedProgramPins(bpffsRoot)
	if err != nil {
		return plan, fmt.Errorf("scan e2e unmanaged program pins: %w", err)
	}
	for _, pin := range progPins {
		plan = append(plan, RemovePin{Path: pin})
	}

	links, err := netlink.LinkList()
	if err != nil {
		return plan, fmt.Errorf("list interfaces: %w", err)
	}
	for _, l := range links {
		name := l.Attrs().Name
		if StaleTestIfaceRe.MatchString(name) {
			plan = append(plan, DeleteIface{Name: name})
		}
	}

	entries, err := os.ReadDir(netnsDir)
	if err != nil {
		if errors.Is(err, fs.ErrNotExist) {
			return plan, nil
		}
		return plan, fmt.Errorf("read %s: %w", netnsDir, err)
	}
	for _, entry := range entries {
		if StaleTestIfaceRe.MatchString(entry.Name()) {
			plan = append(plan, DeleteNetns{Name: entry.Name(), Dir: netnsDir})
		}
	}

	// The harness's TEST-NET-2 policy rule is global state shared
	// by every pair (see internal/testnetroute); it is removed
	// here rather than at pair release so parallel scripts cannot
	// race one pair's teardown against another's traffic. The
	// match is by destination and table at any preference, so
	// rules installed under a custom BPFMAN_E2E_POLICY_RULE_PREF
	// are swept too.
	rules, err := testnetroute.Installed()
	if err != nil {
		return plan, fmt.Errorf("scan test-net policy rules: %w", err)
	}
	for _, r := range rules {
		plan = append(plan, DeleteTestNetRule{Pref: r.Priority})
	}

	return plan, nil
}

// CleanupStaleInterfaces is a Scan-then-Apply convenience for
// callers (notably the e2e suite's TestMain pre-flight) that
// just want any residue gone. Returns the Plan that was applied
// and the per-action failures (empty when every action
// succeeded); the plan is empty when there was no residue at
// scan time. Idempotent; safe to call as a pre-flight.
func CleanupStaleInterfaces(bpffsRoot, netnsDir string) (Plan, []ActionFailure, error) {
	plan, err := ScanE2EResidue(bpffsRoot, netnsDir)
	if err != nil {
		return plan, nil, err
	}
	if plan.Empty() {
		return plan, nil, nil
	}
	return plan, plan.Apply(), nil
}
