---
apiVersion: bpfman.io/v1alpha1
kind: ClusterBpfApplication
metadata:
  labels:
    app.kubernetes.io/name: tcxprogram
  name: go-tcx-counter-example
spec:
  # Select all nodes
  nodeSelector: {}
  byteCode:
    image:
      url: quay.io/bpfman-bytecode/go-tcx-counter:latest
  programs:
    - name: tcx_stats
      type: TCX
      tcx:
        links:
          - interfaceSelector:
              primaryNodeInterface: true
            priority: 55
            direction: Ingress
