FROM golang:1.19 as gocounter-build

RUN apt-get update && apt-get install -y \
 clang \
 gcc-multilib \
 libbpf-dev

RUN go install github.com/cilium/ebpf/cmd/bpf2go@master

WORKDIR /usr/src/bpfman/
COPY ./ /usr/src/bpfman/

WORKDIR /usr/src/bpfman/examples/go-xdp-counter

# Compile gocounter
RUN go build

FROM registry.fedoraproject.org/fedora-minimal:latest

COPY --from=gocounter-build  /usr/src/bpfman/examples/go-xdp-counter/go-xdp-counter .

ENTRYPOINT ["./go-xdp-counter", "--crd"]
