---
apiVersion: bpfman.io/v1alpha1
kind: TcProgram
metadata:
  labels:
    app.kubernetes.io/name: tcprogram
  name: go-tc-counter-example
spec:
  bpffunctionname: stats
  # Select all nodes
  nodeselector: {}
  interfaceselector:
    primarynodeinterface: true
  priority: 55
  direction: ingress
  bytecode:
    image:
      url: quay.io/bpfman-bytecode/go-tc-counter:latest
