/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	apisv1alpha1 "github.com/redhat-et/bpfd/bpfd-operator/apis/v1alpha1"
	versioned "github.com/redhat-et/bpfd/bpfd-operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/redhat-et/bpfd/bpfd-operator/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/redhat-et/bpfd/bpfd-operator/pkg/client/listers/apis/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// BpfProgramConfigInformer provides access to a shared informer and lister for
// BpfProgramConfigs.
type BpfProgramConfigInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.BpfProgramConfigLister
}

type bpfProgramConfigInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewBpfProgramConfigInformer constructs a new informer for BpfProgramConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewBpfProgramConfigInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredBpfProgramConfigInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredBpfProgramConfigInformer constructs a new informer for BpfProgramConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredBpfProgramConfigInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.BpfdV1alpha1().BpfProgramConfigs().List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.BpfdV1alpha1().BpfProgramConfigs().Watch(context.TODO(), options)
			},
		},
		&apisv1alpha1.BpfProgramConfig{},
		resyncPeriod,
		indexers,
	)
}

func (f *bpfProgramConfigInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredBpfProgramConfigInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *bpfProgramConfigInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apisv1alpha1.BpfProgramConfig{}, f.defaultInformer)
}

func (f *bpfProgramConfigInformer) Lister() v1alpha1.BpfProgramConfigLister {
	return v1alpha1.NewBpfProgramConfigLister(f.Informer().GetIndexer())
}
