apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tcx-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: bpfman-user
subjects:
  - kind: ServiceAccount
    name: bpfman-app-go-tcx-counter
    namespace: go-tcx-counter
