---
# Patch the bytecode.yaml to change image and tag on the "url" field
# (which is an image) to new value.
- op: replace
  path: /spec/bytecode/image/url
  value: quay.io/bpfman-bytecode/go-tcx-counter:latest
