apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Patch the deployment.yaml to change container image in Daemonset
# to new tag on the image.
images:
  - name: quay.io/bpfman-userspace/go-uretprobe-counter
    newName: quay.io/bpfman-userspace/go-uretprobe-counter
    newTag: latest
# Patch the bytecode.yaml to change tag on the "url" field (which is an
# image) to new value. Since this is being done with an environment
# variable and using sed to replace, moved to patch.yaml.env which is
# converted to patch.yaml using the sed command in Makefile.
patches:
  - path: patch.yaml
    target:
      kind: uprobeProgram
      name: go-uretprobe-counter-example
resources:
  - ../../base/go-uretprobe-counter
