/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/redhat-et/bpfd/bpfd-operator/apis/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeBpfProgramConfigs implements BpfProgramConfigInterface
type FakeBpfProgramConfigs struct {
	Fake *FakeBpfdV1alpha1
}

var bpfprogramconfigsResource = schema.GroupVersionResource{Group: "bpfd.io", Version: "v1alpha1", Resource: "bpfprogramconfigs"}

var bpfprogramconfigsKind = schema.GroupVersionKind{Group: "bpfd.io", Version: "v1alpha1", Kind: "BpfProgramConfig"}

// Get takes name of the bpfProgramConfig, and returns the corresponding bpfProgramConfig object, and an error if there is any.
func (c *FakeBpfProgramConfigs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.BpfProgramConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(bpfprogramconfigsResource, name), &v1alpha1.BpfProgramConfig{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BpfProgramConfig), err
}

// List takes label and field selectors, and returns the list of BpfProgramConfigs that match those selectors.
func (c *FakeBpfProgramConfigs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.BpfProgramConfigList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(bpfprogramconfigsResource, bpfprogramconfigsKind, opts), &v1alpha1.BpfProgramConfigList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.BpfProgramConfigList{ListMeta: obj.(*v1alpha1.BpfProgramConfigList).ListMeta}
	for _, item := range obj.(*v1alpha1.BpfProgramConfigList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested bpfProgramConfigs.
func (c *FakeBpfProgramConfigs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(bpfprogramconfigsResource, opts))
}

// Create takes the representation of a bpfProgramConfig and creates it.  Returns the server's representation of the bpfProgramConfig, and an error, if there is any.
func (c *FakeBpfProgramConfigs) Create(ctx context.Context, bpfProgramConfig *v1alpha1.BpfProgramConfig, opts v1.CreateOptions) (result *v1alpha1.BpfProgramConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(bpfprogramconfigsResource, bpfProgramConfig), &v1alpha1.BpfProgramConfig{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BpfProgramConfig), err
}

// Update takes the representation of a bpfProgramConfig and updates it. Returns the server's representation of the bpfProgramConfig, and an error, if there is any.
func (c *FakeBpfProgramConfigs) Update(ctx context.Context, bpfProgramConfig *v1alpha1.BpfProgramConfig, opts v1.UpdateOptions) (result *v1alpha1.BpfProgramConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(bpfprogramconfigsResource, bpfProgramConfig), &v1alpha1.BpfProgramConfig{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BpfProgramConfig), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeBpfProgramConfigs) UpdateStatus(ctx context.Context, bpfProgramConfig *v1alpha1.BpfProgramConfig, opts v1.UpdateOptions) (*v1alpha1.BpfProgramConfig, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(bpfprogramconfigsResource, "status", bpfProgramConfig), &v1alpha1.BpfProgramConfig{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BpfProgramConfig), err
}

// Delete takes name of the bpfProgramConfig and deletes it. Returns an error if one occurs.
func (c *FakeBpfProgramConfigs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(bpfprogramconfigsResource, name, opts), &v1alpha1.BpfProgramConfig{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeBpfProgramConfigs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(bpfprogramconfigsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.BpfProgramConfigList{})
	return err
}

// Patch applies the patch and returns the patched bpfProgramConfig.
func (c *FakeBpfProgramConfigs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.BpfProgramConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(bpfprogramconfigsResource, name, pt, data, subresources...), &v1alpha1.BpfProgramConfig{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BpfProgramConfig), err
}
