# Generated by rust2rpm 20
%bcond_without check

%global crate bpfman

Name:           rust-%{crate}
Version:        0.1.0
Release:        %autorelease
Summary:        # FIXME

# Upstream license specification: None
License:        # FIXME

URL:            https://crates.io/crates/bpfman
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging

%global _description %{expand:
%{summary}.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE-APACHE LICENSE-GPL2 LICENSE-MIT libbpf/LICENSE libbpf/LICENSE.BSD-2-Clause libbpf/LICENSE.LGPL-2.1
%doc README.md
%{_bindir}/bpfman

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
