//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ByteCodeSource) DeepCopyInto(out *ByteCodeSource) {
	*out = *in
	if in.ImageUrl != nil {
		in, out := &in.ImageUrl, &out.ImageUrl
		*out = new(string)
		**out = **in
	}
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ByteCodeSource.
func (in *ByteCodeSource) DeepCopy() *ByteCodeSource {
	if in == nil {
		return nil
	}
	out := new(ByteCodeSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EbpfProgram) DeepCopyInto(out *EbpfProgram) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EbpfProgram.
func (in *EbpfProgram) DeepCopy() *EbpfProgram {
	if in == nil {
		return nil
	}
	out := new(EbpfProgram)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EbpfProgram) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EbpfProgramAttachPoint) DeepCopyInto(out *EbpfProgramAttachPoint) {
	*out = *in
	if in.Interface != nil {
		in, out := &in.Interface, &out.Interface
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EbpfProgramAttachPoint.
func (in *EbpfProgramAttachPoint) DeepCopy() *EbpfProgramAttachPoint {
	if in == nil {
		return nil
	}
	out := new(EbpfProgramAttachPoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EbpfProgramConfig) DeepCopyInto(out *EbpfProgramConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EbpfProgramConfig.
func (in *EbpfProgramConfig) DeepCopy() *EbpfProgramConfig {
	if in == nil {
		return nil
	}
	out := new(EbpfProgramConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EbpfProgramConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EbpfProgramConfigList) DeepCopyInto(out *EbpfProgramConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EbpfProgramConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EbpfProgramConfigList.
func (in *EbpfProgramConfigList) DeepCopy() *EbpfProgramConfigList {
	if in == nil {
		return nil
	}
	out := new(EbpfProgramConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EbpfProgramConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EbpfProgramConfigSpec) DeepCopyInto(out *EbpfProgramConfigSpec) {
	*out = *in
	in.NodeSelector.DeepCopyInto(&out.NodeSelector)
	in.AttachPoint.DeepCopyInto(&out.AttachPoint)
	in.ByteCode.DeepCopyInto(&out.ByteCode)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EbpfProgramConfigSpec.
func (in *EbpfProgramConfigSpec) DeepCopy() *EbpfProgramConfigSpec {
	if in == nil {
		return nil
	}
	out := new(EbpfProgramConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EbpfProgramConfigStatus) DeepCopyInto(out *EbpfProgramConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EbpfProgramConfigStatus.
func (in *EbpfProgramConfigStatus) DeepCopy() *EbpfProgramConfigStatus {
	if in == nil {
		return nil
	}
	out := new(EbpfProgramConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EbpfProgramList) DeepCopyInto(out *EbpfProgramList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EbpfProgram, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EbpfProgramList.
func (in *EbpfProgramList) DeepCopy() *EbpfProgramList {
	if in == nil {
		return nil
	}
	out := new(EbpfProgramList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EbpfProgramList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EbpfProgramSpec) DeepCopyInto(out *EbpfProgramSpec) {
	*out = *in
	if in.ProgramMap != nil {
		in, out := &in.ProgramMap, &out.ProgramMap
		*out = make(map[string]EbpfProgramAttachPoint, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.MapPinPoints != nil {
		in, out := &in.MapPinPoints, &out.MapPinPoints
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EbpfProgramSpec.
func (in *EbpfProgramSpec) DeepCopy() *EbpfProgramSpec {
	if in == nil {
		return nil
	}
	out := new(EbpfProgramSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EbpfProgramStatus) DeepCopyInto(out *EbpfProgramStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EbpfProgramStatus.
func (in *EbpfProgramStatus) DeepCopy() *EbpfProgramStatus {
	if in == nil {
		return nil
	}
	out := new(EbpfProgramStatus)
	in.DeepCopyInto(out)
	return out
}
