FROM golang:1.19 as bpfd-agent-build

WORKDIR /usr/src/bpfd/
COPY ./ /usr/src/bpfd/

WORKDIR /usr/src/bpfd/

# Compile bpfd-agent statically since we're running in a scratch container
RUN  cd ./bpfd-operator && CGO_ENABLED=0 go build -a -ldflags '-extldflags "-static"' -o ./bin/bpfd-agent ./cmd/bpfd-agent/main.go

FROM scratch

COPY --from=bpfd-agent-build  /usr/src/bpfd/bpfd-operator/bin/bpfd-agent .

ENTRYPOINT ["./bpfd-agent"]