FROM rustlang/rust:nightly as bpfd-agent-build

RUN apt-get update && apt-get install -y protobuf-compiler musl-tools

WORKDIR /usr/src/bpfd
COPY ./ /usr/src/bpfd

RUN rustup target add x86_64-unknown-linux-musl

# Compile only bpfctl
RUN cargo build -p bpfd-agent --release --target x86_64-unknown-linux-musl

FROM scratch

COPY --from=bpfd-agent-build  /usr/src/bpfd/target/x86_64-unknown-linux-musl/release/bpfd-agent .

ENTRYPOINT ["./bpfd-agent"]