FROM rustlang/rust:nightly as bpfctl-build
WORKDIR /usr/src/bpfd
COPY ./ /usr/src/bpfd

RUN apt-get update && apt-get install -y protobuf-compiler musl-tools

RUN rustup target add x86_64-unknown-linux-musl

# Compile only bpfctl
RUN cargo build -p bpfctl --release --target x86_64-unknown-linux-musl

FROM scratch

COPY --from=bpfctl-build  /usr/src/bpfd/target/x86_64-unknown-linux-musl/release/bpfctl .

ENTRYPOINT ["./bpfctl"]
